# -*- coding: utf-8 -*-
"""Sanskrit_Character_Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnXcXFhrK3lKxLencI1fHDUo1P9mDkBR

### **Sanskrit Handwritten Character Classification using Multi-Class Logistic Regression**

Step 1— Connect Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""STEP 2 — Import Libraries"""

import os
import io
import zipfile
import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

import joblib

"""STEP 3 — Give Dataset Path"""

ZIP_PATH = "/content/drive/MyDrive/CIS/devanagari+handwritten+character+dataset.zip"

print("Dataset found:", os.path.exists(ZIP_PATH))

zip_file = zipfile.ZipFile(ZIP_PATH, 'r')

all_files = zip_file.namelist()

print("Total files:", len(all_files))

"""STEP 5 — Find Images"""

png_files = [
    file for file in all_files
    if file.lower().endswith(".png")
]

print("Total PNG images:", len(png_files))

"""STEP 6 — Separate Train & Test"""

train_files = [
    file for file in png_files
    if "Train" in file
]

test_files = [
    file for file in png_files
    if "Test" in file
]

print("Training images:", len(train_files))
print("Testing images:", len(test_files))

"""Step 7-Find Character Classes"""

def get_class_name(file_name):
    return file_name.strip("/").split("/")[-2]

classes = sorted(
    set(get_class_name(file) for file in png_files)
)

print("Number of classes:", len(classes))
print("Classes:", classes)

"""Step 8 -Create Numerical Labels"""

class_to_id = {
    class_name: index
    for index, class_name in enumerate(classes)
}

id_to_class = {
    index: class_name
    for class_name, index in class_to_id.items()
}

print(class_to_id)

"""STEP 9 — Preprocess the Images"""

def load_images_from_zip(file_list):

    X = []
    y = []

    for file_name in file_list:

        image_data = zip_file.read(file_name)

        image = Image.open(
            io.BytesIO(image_data)
        ).convert("L")

        image = image.resize((32, 32))

        image_array = np.array(image) / 255.0

        image_array = image_array.flatten()

        class_name = get_class_name(file_name)

        label = class_to_id[class_name]

        X.append(image_array)
        y.append(label)

    return np.array(X), np.array(y)

print("Preprocessing function ready!")

"""STEP 10 — Load Training Images"""

X_train, y_train = load_images_from_zip(train_files)

print("Training data shape:", X_train.shape)
print("Training labels shape:", y_train.shape)

"""STEP 11 — Load Testing Images"""

X_test, y_test = load_images_from_zip(test_files)

print("Testing data shape:", X_test.shape)
print("Testing labels shape:", y_test.shape)

"""STEP 12 — Checking the Dataset"""

print("Number of classes:", len(classes))
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Image size: 32 × 32")
print("Features per image:", X_train.shape[1])

"""STEP 13 — Show Sample Images"""

plt.figure(figsize=(12, 6))

for i in range(10):
    plt.subplot(2, 5, i + 1)

    image = X_train[i].reshape(32, 32)

    plt.imshow(image, cmap="gray")
    plt.title(id_to_class[y_train[i]])
    plt.axis("off")

plt.tight_layout()
plt.show()

"""STEP 14 — Train the Logistic Regression Model"""

model = LogisticRegression(
    solver="lbfgs",
    max_iter=1000,
    multi_class="multinomial"
)

model.fit(X_train, y_train)

print("Model training completed!")

"""STEP 15 — Make Predictions"""

y_pred = model.predict(X_test)

print("Predictions completed!")

"""STEP 16 — Calculate Accuracy"""

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")

"""STEP 17 — Precision, Recall & F1 Score"""

precision = precision_score(
    y_test, y_pred, average="weighted"
)

recall = recall_score(
    y_test, y_pred, average="weighted"
)

f1 = f1_score(
    y_test, y_pred, average="weighted"
)

print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1 Score:", round(f1, 4))

"""STEP 18 — Classification Report"""

report = classification_report(
    y_test,
    y_pred,
    target_names=classes
)

print(report)

"""STEP 19 — Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, cmap="Blues",
            xticklabels=classes,
            yticklabels=classes)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Sanskrit Character Confusion Matrix")
plt.show()

"""STEP 20 — Compare Actual vs Predicted"""

plt.figure(figsize=(12, 6))

for i in range(10):
    plt.subplot(2, 5, i + 1)

    image = X_test[i].reshape(32, 32)

    plt.imshow(image, cmap="gray")

    actual = id_to_class[y_test[i]]
    predicted = id_to_class[y_pred[i]]

    plt.title(
        f"Actual: {actual}\nPredicted: {predicted}"
    )

    plt.axis("off")

plt.tight_layout()
plt.show()

"""STEP 21 — Prediction Confidence"""

probabilities = model.predict_proba(X_test[:10])

predicted_classes = model.predict(X_test[:10])

for i in range(10):

    predicted_id = predicted_classes[i]

    confidence = probabilities[i][predicted_id]

    print(
        f"Image {i + 1}: "
        f"{id_to_class[predicted_id]} "
        f"({confidence * 100:.2f}%)"
    )

print("FINAL RESULTS")

print("Number of Classes:", len(classes))
print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

print("Accuracy:", round(accuracy * 100, 2), "%")
print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1 Score:", round(f1, 4))